name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            if [ ! -d "${{ secrets.APP_DIR }}" ]; then
              git clone https://github.com/Nagaraj411/ai-fastapi-project.git ${{ secrets.APP_DIR }}
            fi

            cd ${{ secrets.APP_DIR }}

            git pull origin main

            docker compose down

            docker compose build

            docker compose up -d